### ISSUE TITLE
No issiue

### ISSUE THREAD

**Issue by Mhmortensen** [Taira87/realistichandlingbyTaira#1]
Can you add last dlc pack too? :D

**Comment by Taira87** [comment]
> Can you add last dlc pack too? :D

Hi mortensen, im in the middle of a study journey with a lot of test at 10th november. I check the last dlc 2 weeks ago, and The artifacts didnt work. I will update in november :D

P.D I can dlc cars one by one but they will be addons cars and not native. So I prefered to wait.

**Comment by Mhmortensen** [comment]
Niiiice man! The handlings er awesome dude. Happy study!
